name: build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-pandoc@v2

    # we use conda instead of setup-python because we need the lapack and blas libraries that come with conda's install
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        miniconda-version: "latest"
        activate-environment: mushi
        auto-activate-base: true
    - run: |
        which python
        which pip

    - name: Install
      run: |
        python -m pip install --upgrade pip
        make install

    - name: Lint
      run: |
        make lint

    - name: Check format with black
      run: |
        black --check mushi

    - name: Test
      run: |
        make test

    - name: Test docs build
      run: |
        make docs
